xforms-engine: resolve build warning for ImportMeta
Resolves build warning:

    error TS2339: Property 'env' does not exist on type 'ImportMeta'.

Closes #444